apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.13.3
  - argocd-namespace.yaml

# Patch argocd-cm ConfigMap for Crossplane compatibility
patches:
  - path: argocd-cm-patch.yaml

namespace: argocd
